# Generated by Django 4.1.3 on 2022-12-11 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_appointment_doctor_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='pateint_username',
            new_name='patient_username',
        ),
    ]
