# Generated by Django 4.1.4 on 2022-12-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_rename_pateint_username_appointment_patient_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='lab_tests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
            ],
        ),
    ]
