# Generated by Django 4.1.4 on 2022-12-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_lab_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='report',
            field=models.FileField(null=True, upload_to='reports'),
        ),
    ]
