# Generated by Django 4.1.4 on 2022-12-16 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_appointment_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='test_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
